---
# handlers file for ansible-rabbitmq
# - name: restart rabbitmq-server
#   service:
#     name: "rabbitmq-server"
#     state: restarted
#   become: true

- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted
  become: yes

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started
  become: yes

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped
  become: yes

